name = "bedrock-simple"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./"

[[d1_databases]]
binding = "claudemax_v4db"
database_name = "claudemax-v4db"
database_id = "eedcc213-cd01-48ba-aba0-1b9af675c485"

[vars]
AWS_REGION = "us-east-1"
ANTHROPIC_MODEL = "us.anthropic.claude-sonnet-4-6"
